//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Task
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string JsonContent { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Predecessor { get; set; }
        public Nullable<int> Activity_Id { get; set; }
    
        public virtual APMT_Activity APMT_Activity { get; set; }
    }
}
