//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Project_User
    {
        public int ID { get; set; }
        public Nullable<int> Project_id { get; set; }
        public Nullable<int> User_company_id { get; set; }
        public Nullable<int> Allowed { get; set; }
    
        public virtual APMT_Company_User APMT_Company_User { get; set; }
    }
}
