//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APMT_Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APMT_Activity()
        {
            this.APMT_Activity_to_Activity = new HashSet<APMT_Activity_to_Activity>();
            this.APMT_Activity_to_Activity1 = new HashSet<APMT_Activity_to_Activity>();
            this.APMT_Task = new HashSet<APMT_Task>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Process_Id { get; set; }
        public Nullable<int> Weigth { get; set; }
        public Nullable<int> Type_id { get; set; }
        public int activity_key { get; set; }
        public string Category { get; set; }
    
        public virtual APMT_Activity_Type APMT_Activity_Type { get; set; }
        public virtual APMT_Process APMT_Process { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Activity_to_Activity> APMT_Activity_to_Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Activity_to_Activity> APMT_Activity_to_Activity1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APMT_Task> APMT_Task { get; set; }
    }
}
